### ISSUE TITLE
Travis giving error

### ISSUE THREAD

**Issue by lubbertkramer** [xirixiz/home-assistant-config#8]
When uploading my config and the changed afvalwjzer to Github it gives an error on line 68, i can't find out what the problem is. Sensor itself is working in Home Assistant

Home Assistant version: 0.88.1
Afvalwijzer: Latest, changed from sensor to afvalwijzer under custom components

Config under sensors:
```
  - platform: mijnafvalwijzer
    postcode: !secret afvalwijzer_postcode
    huisnummer: !secret afvalwijzer_huisnummer
```

Line 68 according to Atom:
`    url = (f"https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode={postcode}&street=&huisnummer={huisnummer}&toevoeging={toevoeging}&platform=phone&langs=nl&")`
```

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/homeassistant/scripts/check_config.py", line 207, in check
    res['components'] = check_ha_config_file(hass)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/homeassistant/scripts/check_config.py", line 374, in check_ha_config_file
    platform = loader.get_platform(hass, domain, p_name)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/homeassistant/loader.py", line 82, in get_platform
    domain=domain, platform=platform_name))
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 693, in exec_module
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/build/lubbertkramer/home_assistant_config/./custom_components/mijnafvalwijzer/sensor.py", line 68
    url = (f"https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode={postcode}&street=&huisnummer={huisnummer}&toevoeging={toevoeging}&platform=phone&langs=nl&")
                                                                                                                                                                       ^
SyntaxError: invalid syntax
Fatal error while loading config: invalid syntax (sensor.py, line 68)
Failed config
  General Errors: 
    - invalid syntax (sensor.py, line 68)
```
![image](https://user-images.githubusercontent.com/8224586/53518508-7eb6dd00-3ad1-11e9-8b14-70e7df11e43a.png)

**Comment by xirixiz** [comment]
Hmm, weird. Can you try to add:

```
logger:
  default: warn
  logs:
    custom_components.sensor.mijnafvalwijzer: debug
```
Maybe you'll notice something useful. Or you could PM me your postal code and housenumber so I can check it for you.

**Comment by xirixiz** [comment]
Ah, I now notice you're using travis-ci? Maybe it's a python version issue as I`m using f-strings in my code (python3).

Check this: https://realpython.com/python-f-strings/

**Comment by xirixiz** [comment]
Example you could use:
https://github.com/danielpalstra/home-assistant-config/blob/master/.travis.yml
